In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.linear_model import Lasso

def one_hot_convert(df, col, drop = 0):
    col = col.lower()
    encoder = LabelBinarizer()
    for i in df[col]:
        if type(i) == str or not np.isnan(i):
            fillna = i
            break
    if type(i)==str:
        fillna = "nan"
    else:
        fillna = -1
    df[col] = df[col].fillna(fillna)
    oneHot = encoder.fit_transform(df[col])
    colnames = [col + '_' + str(_).lower() for _ in sorted(list(df[col].unique()))]
    tmp = pd.DataFrame(oneHot, columns=colnames)
    tmp = tmp.set_index(df.index)
    df = pd.concat([df, tmp], axis = 1)
    if col +"_"+ str(fillna) in df.columns:
        df = df.drop(col +"_"+ str(fillna), axis = 1)
    if drop : 
        df = df.drop(col, axis = 1)
    return df

def to_num(df, col, sort_flag = 0, reference = []):
    global categ_dico
    col = col.lower()
    if not len(reference):
        reference = list(df[col].unique())
    if sort_flag :
        reference.sort()
    df[col] = df[col].apply(lambda x:reference.index(x))
    categ_dico[col] = reference
    return reference

In [2]:
CINE = pd.read_csv("CINEMASHS2.csv", low_memory = 0, index_col = 0)
CINE2 = pd.read_csv("CINE2.csv", low_memory = 0, index_col = 0)
categ_dico = {}
CINE_EX = pd.DataFrame(CINE)
CINE.columns = [_.lower() for _ in list(CINE.columns)]

In [8]:
#to_num(CINE, "Genre")
cine = one_hot_convert(CINE, "Genre", drop = 1)
cine = one_hot_convert(cine, "produc", drop = 1)
cine = one_hot_convert(cine, "distrib", drop = 1)
cine = one_hot_convert(cine, "origine", drop = 1)
cine = cine.drop("categ.copies", 1)
#cine.devis = cine.devis.fillna(0)
to_num(CINE, "distrib")
to_num(CINE, "produc", reference = categ_dico["distrib"])
to_num(CINE, "origine")
to_num(CINE, "coc")
tmp = CINE["categ.copies"].unique()
mask = [6, 0, 5, 2, 1, 4, 3, 7, 8, 9]
tmp = tmp[mask]
to_num(CINE, "categ.copies", reference = list(tmp))
Y = cine.entrees
X = cine

In [9]:
X = cine.dropna()

In [102]:
for i in X.columns:
    if len(X[i])!= len(X[i].dropna()):
        print(i)

na_columns=X.columns[X.isna().any()]
X[na_columns].isna().sum()

Series([], dtype: float64)

In [10]:
def R2(Yreal, Ysoum):
    E = Yreal-Ysoum
    y = Yreal - Yreal.mean()
    return 1 - (E*E).sum()/(y*y).sum()

In [11]:
na_row = X[X.devis.isna()].index
X = X.drop(na_row)
na_row = X[X.critlegit.isna()].index
X = X.drop(na_row)
na_row = X[X.critpopu.isna()].index
X = X.drop(na_row)
na_row = X[X.copies.isna()].index
X = X.drop(na_row)
na_row = X[X.duree.isna()].index
X = X.drop(na_row)
na_row = X[X.entrees.isna()].index
X = X.drop(na_row)
Y = X.entrees
X = X.drop("entrees", 1)

KeyError: 'distrib'

In [135]:
Y = np.log(Y+1)

In [68]:
cine = one_hot_convert(CINE, "Genre", drop = 1)

In [18]:
lasso_reg = Lasso(alpha = 100, normalize=0)
lasso_reg.fit(X, Y)
Ypred = lasso_reg.predict(X)

In [20]:
R2(Y, Ypred)

0.6039361056916963

In [147]:
for i in range(len(col_id)):
    if col_id[i]: 
        print (X.columns[i], col_id[i])

copies 0.0007875572277305948
devis 1.3989823117029244e-09
duree 0.00014529054796213648
rk_entrees 0.07676620063168361
rk_copies -0.001705434205400505
rk_devis -0.0017148872457158606

In [151]:
(Y*Y).sum()

703254.9620673488

In [130]:
np.log(1)

0.0

In [108]:
X.head()

,copies,devis,ae,rd,coc,rang,duree,cannes,regard,quinzaine,...,distrib_7,distrib_8,distrib_9,origine_0,origine_1,origine_2,origine_3,origine_4,origine_5,origine_6
13,124.0,6536000.0,1,0,0,1.0,89.0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,312.0,29412000.0,0,0,4,12.0,104.0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
17,371.0,21242000.0,1,0,0,9.0,105.0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
21,220.0,16340000.0,1,0,0,2.0,115.0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
24,102.0,5719000.0,0,0,4,2.0,97.0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [7]:
pca = PCA(n_components = 2)
#r = pca.fit_transform(C)

encoder = LabelBinarizer()
oneHot = encoder.fit_transform(CINE.Genre)

In [58]:
cine.head(10)

,entrees,copies,devis,distrib,produc,origine,ae,rd,coc,rang,...,categ.copies,genre_action,genre_animation,genre_autre,genre_comdram,genre_comédie,genre_documentaire,genre_drame,genre_horreur,genre_sci-fi
1,2191.0,6.0,NaN,NotAv,9,MINO,0,0,TP,4.0,...,"[5,10)",0,0,0,1,0,0,0,0,0
2,20542.0,80.0,NaN,NotAv,NotAv,F100,0,0,TP,2.0,...,"[50,100)",0,0,0,0,1,0,0,0,0
3,15454.0,30.0,NaN,NotAv,tvFR,F100,0,0,TP,2.0,...,"[20,50)",0,0,0,1,0,0,0,0,0
4,2832.0,6.0,NaN,NotAv,NotAv,EUROPE,1,0,16,1.0,...,"[5,10)",0,0,0,0,0,0,1,0,0
5,177519.0,220.0,NaN,NotAv,tvFR,F100,1,0,TPA,7.0,...,"[200,400)",0,0,0,1,0,0,0,0,0
6,45795.0,35.0,NaN,NotAv,NotAv,F100,1,1,TP,3.0,...,"[20,50)",0,0,0,0,0,0,1,0,0
7,62796.0,100.0,NaN,NotAv,tvFR,NaN,1,0,NotAv,3.0,...,"[100,200)",0,0,0,1,0,0,0,0,0
8,2912.0,10.0,NaN,NotAv,NotAv,MAJO,1,1,TP,8.0,...,"[10,20)",0,0,0,1,0,0,0,0,0
9,301.0,5.0,NaN,NotAv,NotAv,EUROPE,0,0,TP,1.0,...,"[5,10)",0,0,0,1,0,0,0,0,0
10,3061.0,6.0,NaN,NotAv,NotAv,MAJO,1,1,TP,5.0,...,"[5,10)",0,0,0,0,0,0,1,0,0

In [9]:
cine = cine.drop("Genre", axis = 1)

In [39]:
cine.insert(1, "remplissage", cine.ENTREES/cine.copies)